Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('ecommerce')->group(function() {
            Route::name('ecommerce.')->group(function() {

                Route::get('dashboard', 'Admin\EcommerceController@index')->name('dashboard');//->middleware('permission:ecommerce-dashboard-read');

                Route::prefix('product-category')->group(function() {
                    Route::name('product-category.')->group(function() {
                        Route::get('/', 'Admin\ProductCategoryController@index')->name('index');
                    });
                });

            });
        });
    });
});

Entities/EcommerceModel.php
<?php

namespace Modules\Ecommerce\Entities;

use App\Models\BaseModel;

class EcommerceModel extends BaseModel
{
    public const DB_TABLE_PREFIX = 'ecom_';
}

Entities/ProductCategory.php
<?php

namespace Modules\Ecommerce\Entities;

use App\Traits\Uuid as TraitsUuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class ProductCategory extends EcommerceModel
{
    use HasFactory, TraitsUuid, SoftDeletes;

    protected $table = EcommerceModel::DB_TABLE_PREFIX . 'product_categories';

    protected $fillable = [
        'name', 'slug', 'description', 'parent_id', 'image'
    ];
    
    
}

Http/Controllers/Admin/EcommerceController.php
<?php

namespace Modules\Ecommerce\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class EcommerceController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('ecommerce::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('ecommerce::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        return view('ecommerce::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        return view('ecommerce::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

Http/Controllers/Admin/ProductCategoryController.php
<?php

namespace Modules\Ecommerce\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Contracts\Support\Renderable;
use Modules\Ecommerce\Entities\ProductCategory;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $params['data'] = ProductCategory::get();
        return view('ecommerce::admin.product-category.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('ecommerce::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('ecommerce::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('ecommerce::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Resources/views/admin/product-category/index.blade.php
@extends('ecommerce::layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('ecommerce.name') !!}
    </p>

    {{ $data }}
@endsection

Resources/views/admin/shared/sidebar.blade.php
@can('ecommerce')
<li class="treeview @if($adminActiveMenu == 'ecommerce') active @endif">
    <a href="#">
        <i class="fa fa-users"></i>
        <span>eCommerce</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            <span class="label label-danger pull-right">
                New
            </span>
        </span>
    </a>
    <ul class="treeview-menu">
        @can('ecommerce-dashboard-read')
        <li class="@if($adminActiveSubMenu == 'dashboard') active @endif">
            <a href="{!! route('ecommerce.dashboard') !!}">
                <i class="fa fa-circle-o"></i> Unit Operation Schedule
                <span class="pull-right-container"></span>
            </a>
        </li>
        @endcan
    </ul>
</li>
@endcan

Resources/views/index.blade.php
@extends('ecommerce::layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('ecommerce.name') !!}
    </p>

    {{-- {{ $config }} --}}
@endsection

Resources/views/layouts/master.blade.php
@extends('layouts.app')